routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', 'home', 301);
Route::get('home', 'StaticPageController@home');
Route::get('about', 'StaticPageController@about')->name("about");

Route::get('signup', 'UserController@create')->name('signup');
Route::post('signup', 'UserController@store');
Route::resource('user', "UserController", ["except" => ["create", "store"]]);

Route::get('login', "SessionController@create")->name('login');
Route::post('login', "SessionController@store");
Route::delete('logout', "SessionController@destroy")->name('logout');

Route::get('password_reset/create', "PasswordResetController@create")->name("reset.create");
Route::post('password_reset', "PasswordResetController@store")->name("reset.store");
Route::get('password_reset/{token}/edit', "PasswordResetController@edit")->name("reset.edit");
Route::patch('password_reset/{token}', "PasswordResetController@update")->name("reset.update");

Route::resource("rekion", "RekionController", ["only" => ["index", "show"]]);

Route::resource("comment", "CommentController", ["only" => ["index", "store", "destroy"]]);

Route::resource("tag", "TagController", ["only" => ["index", "store", "destroy"]]);

Route::resource("favorite", "FavoriteController", ["only" => ["store", "destroy"]]);

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

/**
 * App\Comment
 *
 * @property int $id
 * @property int $rekion_id
 * @property string $text
 * @property int $user_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereRekionId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereText($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Comment whereUserId($value)
 * @mixin \Eloquent
 * @property-read \App\User $user
 */
class Comment extends Model
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('created_at', "desc");
        });
    }

    public function user()
    {
        return $this->belongsTo("App\User");
    }

    public function rekion()
    {
        return $this->belongsTo("App\Rekion");
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('ajax')->only(["index", "store", "destroy"]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->validate([
            "rekion_id" => "required|exists:rekions,id"
        ]);

        $comments = Comment::where("rekion_id", $request->rekion_id)->get();
        return view("comment.index")->with("comments", $comments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "comment" => "required|max:140",
            "rekion_id" => "required|exists:rekions,id"
        ]);

        $comment = new Comment;
        $comment->text = $request->comment;
        $comment->rekion_id = $request->rekion_id;
        Auth::user()->comments()->save($comment);
        return redirect()->route("comment.index", ["rekion_id" => $request->rekion_id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('delete', $comment);

        $comment->delete();
        return "";
    }
}

resources/views/comment/comment.blade.php
<li class="list-group-item" id="commentListItem{{ $comment->id }}">
    <div class="media">
        @if (Request::is("user/*"))
            {{ Html::image(asset("img/thumbnail001.jpg"), "", ["class" => "d-flex mr-3", "width" => "80", "height" => "80"]) }}
        @else
            <a href="{{ route("user.show", $comment->user->id) }}">{!! gravatar_for($comment->user, ["size" => 50]) !!}</a>
        @endif
        <div class="media-body">
            @if (Request::is("user/*"))
                {{ Html::linkRoute("rekion.show", $comment->rekion->title, [$comment->rekion_id]) }}
            @else
                {{ Html::linkRoute("user.show", $comment->user->name, [$comment->user->id]) }}
            @endif
            {{ time_ago_in_words($comment->created_at) }}
            <br>
            {{ $comment->text }}
        @can ("delete", $comment)
            {{ Form::button("削除", ["class"=> "btn btn-outline-primary btn-sm deleteComment", "data-comment-id" => "{$comment->id}"]) }}
        @endif
        </div>
    </div>
</li>

resources/views/comment/index.blade.php
<ul class="list-group-flush pl-0" id="commentList">
    @each('comment.comment', $comments, "comment")
</ul>

<button type="button" id="more_item" class="btn btn-primary">もっと見る</button>

<script>
    (function($) {
        $(function () {
            let commentList = $("#commentList").children('div');
            let currentDispCount = 0;
            let maxDispCount = commentList.length;

            $("#more_item").click(function () {
                let newCount = currentDispCount + 5;

                $(commentList).each(function (i, elem) {
                    if(currentDispCount <= i && i < newCount) {
                        $(this).removeClass("d-none");
                        currentDispCount++;
                    }
                });

                if(maxDispCount<= newCount) {
                    $(this).hide();
                }

                return false;
            });

            $(commentList).each(function (i, elem) {
                $(this).addClass("d-none");
            });

            $("#more_item").click();

            $(".deleteComment").click(function () {
                if (!window.confirm('コメントを削除しますか?')) {
                    return false;
                }
                let commentId = $(this).attr("data-comment-id");
                $.ajax({
                    type: "post",
                    url: "../comment/" + commentId,
                    data: {_method: "delete"}
                }).done(function (response) {
                    $("#commentListItem" + commentId).remove();
                }).fail(function (error) {
                    console.log(error);
                });
            });
        });
    }(jQuery));
</script>